# Configuración de Netlify para Marphil Beauty Studio

[build]
  publish = "/" # Directorio que se desplegará (raíz del proyecto)

# Configuración para redirecciones y encabezados personalizados
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de encabezados para mejorar la seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"